name: Deploy video module

on:
  workflow_call:
    
jobs:
  deploy-amd64-to-ACA:
    name: deploy the image to ACA
    runs-on: ubuntu-latest
    
    env:
      RESOURCE_GROUP: "MVPSession"
      LOCATION: "westeurope"
      CONTAINERAPPS_ENVIRONMENT: "ai-tt-env"
      CONTAINERAPPS_NAME: "facedetection-app"
      CONTAINERAPPSSERVER_NAME: "facedetection-server"
      ARCH: "amd64"
      DOCKER_REPO: "totosan"

    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: prepare AZ EXTENSION
      run: az extension add --name containerapp

    - name: create container app environment
      if: ${{ env.ARCH == 'amd64' }}
      run: |
        az containerapp env create \
        --name $CONTAINERAPPS_ENVIRONMENT \
        --resource-group $RESOURCE_GROUP \
        --location $LOCATION

    - name: create container app with image running
      if: ${{ env.ARCH == 'amd64' }}
      run: |
        az containerapp create \
          --image $DOCKER_REPO/facedetection:$ARCH-preview \
          --name $CONTAINERAPPS_NAME \
          --resource-group $RESOURCE_GROUP \
          --environment $CONTAINERAPPS_ENVIRONMENT \
          --ingress external\
          --target-port 8080\
          --cpu 2.0\
          --memory 4.0Gi \
          --min-replicas 1 \
          --max-replicas 1 \
          --enable-dapr \
          --dapr-app-port 8080 \
          --dapr-app-id faceclient
