name: Build video processing images

on:
  push:
    branches: [ master ]
    paths: 
      - '!faceDetectApp/**'
      - '!.yml'
      
  workflow_dispatch:
          
jobs:
  build-container:
    continue-on-error: true
    strategy:
      matrix:
        include:
          - architecture: amd64
            synonym: "amd64"
            runson: ubuntu-latest 
          - architecture: arm64
            synonym: "aarch64"
            runson: nvidia-gpu
    runs-on: ${{ matrix.runson }}

    env:
      DOCKER_REPO: "totosan"
      VIDEO_PATH: "https://youtu.be/G1VvHZ25j_k"
      ARCH: ${{ matrix.architecture }}
      DAPR_USED: True      

    steps:
    - uses: actions/checkout@v3
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Login to docker.io
      run: sudo docker login -u ${{ secrets.DOCKER_USER }} --password-stin ${{ secrets.DOCKER_PWD }} -Y
  
    - uses: satackey/action-docker-layer-caching@v0.0.11
      if: ${{ matrix.architecture == 'amd64' }}
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true
      with:
        key: facedetection-${{ matrix.architecture }}-{hash}
        restore-keys: |
          facedetection-${{ matrix.architecture }}-

#    - name: prepare for x-build
#      run: |
#        sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
#        sudo docker buildx create --name multiarch --driver docker-container --use
#        sudo docker buildx inspect --bootstrap
    - name: if, build on Jetson Nano, take different Dockerfile
      id: dockerfile
      run: |
        if ${{ matrix.architecture == 'arm64' }}
          echo "::set-output name=filename::Dockerfile-arm64xbuild"
        else
          echo "::set-output name=filename::Dockerfile-arm64"
        fi

    - name: Build the Docker image
      run: |
        sudo docker build . --file ./Dockers/${{ steps.dockerfile.extension }} \
        --build-arg VIDEO_PATH=$VIDEO_PATH \
        --build-arg DAPR_USED=$DAPR_USED \
        --tag $DOCKER_REPO/facedetection:${{ matrix.architecture }}-preview 
    - name: Push the image
      run: |
        sudo docker push $DOCKER_REPO/facedetection:${{ matrix.architecture }}-preview

  call_deploy_job:
    needs: build-container
    uses: ./.github/workflows/deploy-facedetection-video.yml
